global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'xslt-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['xslt-service:8080']
        labels:
          application: 'mersel-xslt-service'
